project_id       = "db-project-456518"
region           = "europe-central2"
credentials_file = "gcp-key.json"
bucket_name      = "db_project_data_bucket"
dataset_id       = "db_project_dataset"
cluster_name     = "db-project-dataproc-cluster"
