name: 'flights_project'
version: '1.0'
config-version: 2

profile: 'my_profile'

model-paths: ["models"]
test-paths: ["test"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:         
  - "target"
  - "dbt_packages"

seeds:
  flights_project:
    airports:
      file: airports.csv
      header: true