version: 2

sources:
  - name: db_project_dataset  # the dataset in BigQuery
    database: db-project-456518  # your BigQuery project ID
    schema: db_project_dataset  # schema (dataset) in BigQuery
    tables:
      - name: flights_data  # table name in BigQuery